version: "3.8"

services:
  backend:
    build: .
    container_name: flask
    networks:
      - net
    ports:
      - 5000:5000
    volumes:
      - .:/test-project:ro
    environment:
      - REDIS_URL=redis://cache:6379/0
    command: "python app.py"
  cache:
    image: redis
    container_name: redis
    networks:
      - net
    ports:
      - 6379:6379
  app:
    build: .
    networks:
      - net
    command: "celery -A tasks.Celery_app worker --pool=solo -l info"
    depends_on:
      - backend
      - cache
    volumes:
      - .:/test-project:ro
    environment:
      - RESULT_BACKEND=redis://cache:6379/0
      - BROKER_URL=redis://cache:6379/0

networks:
  net:
    name: frnet
    driver: bridge
